services:
  db:
    container_name: db
    image: mysql:8.0.31
    restart: unless-stopped
    env_file:
      - ./.env
    expose:
      - 3306
    environment:
      MYSQL_DATABASE: $MYSQLDB_DATABASE
      MYSQL_ROOT_USER: $MYSQLDB_ROOT_USER
      MYSQL_ROOT_PASSWORD: $MYSQLDB_ROOT_PASSWORD
    ports:
      - ${MYSQLDB_LOCAL_PORT}:${MYSQLDB_DOCKER_PORT}
    healthcheck:
          test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
          interval: 30s
          timeout: 30s
          retries: 3
  app:
    depends_on:
      - db
    image: car
    restart: on-failure
    container_name: app
    build: .
    env_file: ./.env
    ports:
      - ${SPRING_LOCAL_PORT}:${SPRING_DOCKER_PORT}
      - ${DEBUG_PORT}:${DEBUG_PORT}
    environment:
      SPRING_APPLICATION_JSON: '{
          "spring.datasource.url" : "jdbc:mysql://db:${MYSQLDB_DOCKER_PORT}/${MYSQLDB_DATABASE}",
          "spring.datasource.username" : "${MYSQLDB_ROOT_USER}",
          "spring.datasource.password" : "${MYSQLDB_ROOT_PASSWORD}",
          "spring.datasource.driver-class-name" : "com.mysql.cj.jdbc.Driver" ,
          "jwt.expiration" : "$JWT_EXPIRATION",
          "jwt.secret" : "$JWT_SECRET",
          "bot.token" : "$BOT_TOKEN"
        }'
      JAVA_TOOL_OPTIONS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005"